name: Build PDFs

on:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Create build directory
        run: mkdir -p build

      - name: pdf kompilieren - cv.tex
        uses: xu-cheng/latex-action@v3
        with:
          root_file: src/cv.tex
          compiler: latexmk
          args: -xelatex -output-directory=build

      - name: pdf kompilieren - document-comparison.tex
        uses: xu-cheng/latex-action@v3
        with:
          root_file: docs/document-comparison.tex
          compiler: latexmk
          args: -xelatex -output-directory=../build

      - name: Upload PDF artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pdf-documents
          path: build/*.pdf
